### PR TITLE
Update to 9.0.0.Beta2

### PR DESCRIPTION
**Pull request by gustavonalle**

### CODE REVIEW

**Comment by slaskawi** [comment]
Unfortunately it seems Docker configuration file changes with the new version... It will take me a while to fix it on CI agents....

**Comment by slaskawi** [comment]
Integrated thanks!

**Comment by gustavonalle** [comment]
@slaskawi Could you please create a tag ```9.0.0.Beta2``` and push it to trigger the build on dockerhub?

**Comment by gustavonalle** [comment]
@slaskawi I added the tag and the build is on its way

**Pull request merged**
