### PR TITLE
CI check

### PR DESCRIPTION
**Pull request by slaskawi**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 9](http://ci.infinispan.org/viewLog.html?buildId=41060&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7b92875459d9293c819bd68cc4223b5885ee80c4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:32:39

Error message is logged

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 12](http://ci.infinispan.org/viewLog.html?buildId=41061&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 3edb6ba98fdaed22c575eba54b1888deb5ffcb85

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 12/slaskawi:CI](http://ci.infinispan.org/viewLog.html?buildId=41061&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 3edb6ba98fdaed22c575eba54b1888deb5ffcb85
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:44

Process exited with code 1

Error message is logged

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 13](http://ci.infinispan.org/viewLog.html?buildId=41063&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for b47d3f17d691958ad391da682c7a933429a77867

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 13/slaskawi:CI](http://ci.infinispan.org/viewLog.html?buildId=41063&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for b47d3f17d691958ad391da682c7a933429a77867
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:46

**Comment by slaskawi** [comment]
@gustavonalle @goldmann - Hey! Could you please review this PR? It's a simplest possible CI check (just to have something that defends us from silly mistakes)

**Comment by goldmann** [comment]
LGTM

**Comment by gustavonalle** [comment]
The script can correctly detect syntax errors in the ```Dockerfile```, but it does not detect errors in the container itself. For example, if the server fails to start, the script exits with error code 0 after 2 minutes.
Also it does not seem to be cleaning up correctly the containers after a failure, causing subsequent name clashes: http://ci.infinispan.org/viewLog.html?buildId=41067&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&tab=buildLog

An interesting testing strategy for the image is by using Travis CI [1], which supports ```docker-compose``` for more advanced multi-container tests, we could combine it with come custom CLI scripts to verify server behaviour, wdyt?

[1] https://docs.travis-ci.com/user/docker/

**Pull request merged**
