### PR TITLE
Update to 9.3.0.Final

### PR DESCRIPTION
**Pull request by galderz**

### CODE REVIEW

**Comment by gustavonalle** [comment]
If CI is good with this, I'm fine as well :)
I think we have a job on Jenkins to release the docker image, did you try to run it?

**Comment by galderz** [comment]
I was going to run it after this got integrated

**Comment by gustavonalle** [comment]
With the jenkins job you should not need to send this PR

**Comment by galderz** [comment]
Oh I see... it wasn't clear.

**Comment by galderz** [comment]
Shall we just close this and execute the jenkins job? CI still running :|

**Comment by galderz** [comment]
CI run for too long. Closing this since I'm releasing it from Jenkins now.

**Comment by gustavonalle** [comment]
Looks like the Jenkins Job is broken

**Comment by gustavonalle** [comment]
>  CI run for too long.

I tried running the tests locally and it also failed (took too long), this could be a problem with the new version

**Pull request closed without merging**
