### PR TITLE
ISPN-6679 Added scripts for Health Check API

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-6679

This PR depends on https://github.com/infinispan/infinispan/pull/4499

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 46](http://ci.infinispan.org/viewLog.html?buildId=41566&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7712708ec46df1885157b817e0524aa78c3783a9

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 46/slaskawi:ISPN-6679/Healthcheck_api](http://ci.infinispan.org/viewLog.html?buildId=41566&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7712708ec46df1885157b817e0524aa78c3783a9
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:37

**Comment by gustavonalle** [comment]
@slaskawi is this still good to go "as is"?

**Comment by slaskawi** [comment]
Probably yes, but I need to retest it with Beta2. Please hold on a moment...

**Comment by gustavonalle** [comment]
Np, I've sent a PR for Beta2 https://github.com/jboss-dockerfiles/infinispan/pull/34

**Comment by slaskawi** [comment]
Rebased

**Pull request merged**
