### PR TITLE
8.2.3.final release

### PR DESCRIPTION
**Pull request by slaskawi**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 25](http://ci.infinispan.org/viewLog.html?buildId=41130&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 55f9c8ea6f67483a5d4a253d306c4600f70ffdba

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 25/slaskawi:8.2.3.final](http://ci.infinispan.org/viewLog.html?buildId=41130&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 55f9c8ea6f67483a5d4a253d306c4600f70ffdba
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:24

Process exited with code 1

Error message is logged

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 30](http://ci.infinispan.org/viewLog.html?buildId=41161&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 0a809381f918d9808b473a3e09c55a89ee25c8e5

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 30/slaskawi:8.2.3.final](http://ci.infinispan.org/viewLog.html?buildId=41161&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 0a809381f918d9808b473a3e09c55a89ee25c8e5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:50

**Comment by gustavonalle** [comment]
This PR should be rebased on top of master

**Comment by slaskawi** [comment]
@gustavonalle Are you sure? I though we wanted to have `8.2.x` branch for stable releases?

**Comment by gustavonalle** [comment]
@slaskawi sorry, my comment was incomplete: we should rebase on top of master AND change the  version to the 8.2.3.Final

**Comment by slaskawi** [comment]
@gustavonalle I rebased it to master and created a PR agains `8.2.x`. It seems Github did the rest for me :) Let's see if it builds...

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 32](http://ci.infinispan.org/viewLog.html?buildId=41181&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for aae40cc525860d698477b3c98f6f1ec06f1b850a

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 32/slaskawi:8.2.3.final](http://ci.infinispan.org/viewLog.html?buildId=41181&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for aae40cc525860d698477b3c98f6f1ec06f1b850a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:35

**Comment by gustavonalle** [comment]
@slaskawi Looks good!

**Pull request merged**
