### PR TITLE
Make all .sh executable

### PR DESCRIPTION
**Pull request by saturnism**
Currently, only standalone.sh is executable.  I'd like to also be able to execute clustered.sh.

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
hi, 
bsdtar does not  respect permissions when piped due to some intrernals, so best approach should be to not pipe but rather download, bsdtar extract and rm the downloaded file.  This way all files will have original permissions, and not only .sh files in bin.

**Comment by goldmann** [comment]
Yes, we should drop `bsdtar` and use `unzip` instead.

**Comment by jorgemoralespou** [comment]
@goldmann I think we should keep bsdtar even the current limitation, not on bsdtar, but any libarchive based tool. But it is in fact a better tool than unzip as can decompress zip, tar, tar.gz files.

**Comment by slaskawi** [comment]
Hey @saturnism ! 

Those scripts have changed recently (we have `domain.sh` for running ISPN in domain mode with the [management console](https://www.youtube.com/watch?v=m_j3dz4k4xA) and `standalone.sh` for everything else).

So I believe you need to use `standalone.sh -c clustered.xml`.

**Comment by gustavonalle** [comment]
The file permission problem will be solved once https://github.com/jboss-dockerfiles/infinispan/pull/14 is integrated

**Comment by gustavonalle** [comment]
This can be closed as #14 was integrated

**Pull request closed without merging**
