### PR TITLE
Upate to Infinispan 9.0.0.CR3

### PR DESCRIPTION
**Pull request by gustavonalle**

### CODE REVIEW

**Comment by slaskawi** [comment]
@gustavonalle REST connection failed during the test?

http://ci.infinispan.org/viewLog.html?buildId=52265&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&tab=buildLog#_focus=758

**Comment by gustavonalle** [comment]
If I launch a container and do 

```curl -X POST -H 'Content-type: text/plain' -d test http://172.17.0.2:8080/rest/default/1```

it works. Is it possible to get the server logs from the CI?

**Comment by slaskawi** [comment]
hmmm I don't think so... you'd probably need to run the script locally...

**Comment by gustavonalle** [comment]
Actually it did not work for me locally. The PUT did not return errors, but the GET came back empty. It seems something changed in the server that broke this behaviour

**Comment by gustavonalle** [comment]
Updated, let's wait for CI

**Comment by gustavonalle** [comment]
Now there was a `connection refused` error, investigating...

**Comment by gustavonalle** [comment]
Should be fine now. The issue was that the ci script was waiting for the pod 'running' state before testing, but it does not mean the server was ready.

**Pull request merged**
