### PR TITLE
Update to 9.3.0.Alpha1

### PR DESCRIPTION
**Pull request by gustavonalle**

### CODE REVIEW

**Comment by slaskawi** [comment]
The CI build failed.... it doesn't seem to be related but...

**Comment by gustavonalle** [comment]
The sha1 file is missing in maven:
``` repositories/releases/org/infinispan/server/infinispan-server-build/9.3.0.Alpha1/infinispan-server-build-9.3.0.Alpha1.zip.sha1],: No such file or directory```

**Comment by slaskawi** [comment]
@tristantarrant That error would be probably for you. Merging..

**Comment by gustavonalle** [comment]
So the issue is that the server CLI is returning an error, and it breaks the CI.

Created https://issues.jboss.org/browse/ISPN-9129

**Pull request merged**
