### PR TITLE
[8.2.x] Squash permission change layer

### PR DESCRIPTION
**Pull request by gustavonalle**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 40](http://ci.infinispan.org/viewLog.html?buildId=41410&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7b0a1b3a656e638f2ac664134714ca46f5905ef6

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 40/gustavonalle:imageSize_8.2.x](http://ci.infinispan.org/viewLog.html?buildId=41410&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7b0a1b3a656e638f2ac664134714ca46f5905ef6
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:46

**Comment by slaskawi** [comment]
Merged and tagged as `8.2.3.Final-2`. Thanks @gustavonalle

**Comment by infinispanrelease** [comment]
Started - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 41](http://ci.infinispan.org/viewLog.html?buildId=41432&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7b0a1b3a656e638f2ac664134714ca46f5905ef6

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Docker image Pull requests JDK8 [Build 41/gustavonalle:imageSize_8.2.x](http://ci.infinispan.org/viewLog.html?buildId=41432&buildTypeId=Infinispan_DockerImagePullRequestsJdk8&guest=1) for 7b0a1b3a656e638f2ac664134714ca46f5905ef6
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:02

**Pull request merged**
