### PR TITLE
Fixed 'oc' path error in OpenShift CI script

### PR DESCRIPTION
**Pull request by slaskawi**

### CODE REVIEW

**Comment by slaskawi** [comment]
Ha! Finally green! http://ci.infinispan.org/viewLog.html?buildTypeId=Infinispan_DockerImagePullRequestsJdk8&buildId=41829

**Comment by slaskawi** [comment]
@gustavonalle Could you please review it when you have a while?

**Comment by gustavonalle** [comment]
LGTM

**Comment by slaskawi** [comment]
Thanks @gustavonalle !

**Pull request merged**
