### PR TITLE
Append custom JAVA_OPTS to the container JAVA_OPTS

### LINKED ISSUE #104: custom JAVA_OPTS are ignored
```docker run -it -e "JAVA_OPTS=-Dprop=value" jboss/infinispan-server```

will not set the JAVA_OPTS and will print a WARNING:

```
JAVA_OPTS already set in environment; overriding default settings with values: -Djava.net.preferIPv4Stack=true -XX:+DisableExplicitGC -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager.LogManager
```

### PR DESCRIPTION
**Pull request by gustavonalle**
Fixes #104

### CODE REVIEW

**Comment by danberindei** [comment]
Will this remove the warning?

**Comment by gustavonalle** [comment]
The warning will still be there, but the external JAVA_OPTS will be passed.
Let me see if I can get rid of it...

**Comment by gustavonalle** [comment]
The warning comes from https://github.com/wildfly/wildfly-core/blob/master/core-feature-pack/src/main/resources/content/bin/standalone.conf#L56, not sure I can silence it from here

**Comment by danberindei** [comment]
Integrated, thanks Gustavo!

**Comment by gustavonalle** [comment]
Cherry-picked into ```master``` as well.

**Pull request merged**
